### ISSUE TITLE
www.freeipa.org down

### ISSUE THREAD

**Issue by redjoker** [freeipa/freeipa-wiki#5]
Attempted accessing from several ISPs, getting the same error message (screenshot attached):

Application is not available

The application is currently not serving requests at this endpoint. It may not have been started or is still starting.

Possible reasons you are seeing this page:

    The host doesn't exist. Make sure the hostname was typed correctly and that a route matching this hostname exists.
    The host exists, but doesn't have a matching path. Check if the URL path was typed correctly and that the route was created using the desired path.
    Route and path matches, but all pods are down. Make sure that the resources exposed by this route (pods, services, deployment configs, etc) have at least one pod running.

![screenshot from 2017-11-22 10-21-17](https://user-images.githubusercontent.com/9204949/33134912-f9e9bdb4-cf6e-11e7-8497-75da2f563241.png)

**Comment by abbra** [comment]
Yes, this is a known issue. We are working on it. Thank you for reporting.

**Comment by mkosek** [comment]
Thanks for the report and sorry for the inconvenience. The wiki got back online couple hours ago.

We had a platform issue, given some bug in the underlying platform - AWS/kube/storage.

**Comment by redjoker** [comment]
👍

On November 22, 2017 2:43:15 PM EST, Martin Kosek <notifications@github.com> wrote:
>Thanks for the report and sorry for the inconvenience. The wiki got
>back online couple hours ago.
>
>We had a platform issue, given some bug in the underlying platform -
>AWS/kube/storage.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/freeipa/freeipa-wiki/issues/5#issuecomment-346454548

Rob Bradley
Two Six Labs, LLC
4350 N Fairfax Dr Ste 410
Arlington, VA 22203
twosixlabs.com
:|:::
